/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/car.glb --transform --simplified --resolution 1024 
Files: public/car.glb [3.55MB] > /Users/fatihyonucuoglu/Documents/GitHub/Fatih/apocalypse/car-transformed.glb [529.41KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} position={[0.019, 0.22, 0.02]} />
    </group>
  )
}

useGLTF.preload('/car-transformed.glb')
