/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { type JSX } from "react";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three/examples/jsm/Addons.js";

type GLTFResult = GLTF & {
  nodes: {
    pCylinder15_standardSurface5_0001: THREE.Mesh;
    pCylinder15_standardSurface5_0001_1: THREE.Mesh;
    pCylinder15_standardSurface5_0001_2: THREE.Mesh;
    pCylinder15_standardSurface5_0001_3: THREE.Mesh;
    pCylinder15_standardSurface5_0001_4: THREE.Mesh;
    pCylinder15_standardSurface5_0001_5: THREE.Mesh;
    pCylinder15_standardSurface5_0001_6: THREE.Mesh;
    pCylinder15_standardSurface5_0001_7: THREE.Mesh;
    pCylinder15_standardSurface5_0001_8: THREE.Mesh;
    pCylinder15_standardSurface5_0001_9: THREE.Mesh;
    pCylinder15_standardSurface5_0001_10: THREE.Mesh;
    pCylinder15_standardSurface5_0001_11: THREE.Mesh;
    pCylinder15_standardSurface5_0: THREE.Mesh;
    pCylinder15_standardSurface5_0_1: THREE.Mesh;
    pCylinder15_standardSurface5_0_2: THREE.Mesh;
    pCylinder15_standardSurface5_0_3: THREE.Mesh;
    pCylinder15_standardSurface5_0_4: THREE.Mesh;
    pCylinder15_standardSurface5_0_5: THREE.Mesh;
    pCylinder15_standardSurface5_0_6: THREE.Mesh;
    pCylinder15_standardSurface5_0_7: THREE.Mesh;
    pCylinder15_standardSurface5_0_8: THREE.Mesh;
    pCylinder15_standardSurface5_0_9: THREE.Mesh;
    pCylinder15_standardSurface5_0_10: THREE.Mesh;
    pCylinder15_standardSurface5_0_11: THREE.Mesh;
  };
  materials: {
    standardSurface5: THREE.MeshStandardMaterial;
    standardSurface8: THREE.MeshStandardMaterial;
    standardSurface6: THREE.MeshStandardMaterial;
    standardSurface18: THREE.MeshStandardMaterial;
    standardSurface22: THREE.MeshStandardMaterial;
    standardSurface4: THREE.MeshStandardMaterial;
    standardSurface19: THREE.MeshStandardMaterial;
    standardSurface3: THREE.MeshStandardMaterial;
    standardSurface11: THREE.MeshStandardMaterial;
    standardSurface15: THREE.MeshStandardMaterial;
    standardSurface7: THREE.MeshStandardMaterial;
    standardSurface12: THREE.MeshStandardMaterial;
  };
};

export default function Guitar(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/guitar.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-2.619, 0.957, 0.894]}
        rotation={[1.604, -0.003, -2.928]}
        scale={0.083}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001.geometry}
          material={materials.standardSurface5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_1.geometry}
          material={materials.standardSurface8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_2.geometry}
          material={materials.standardSurface6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_3.geometry}
          material={materials.standardSurface18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_4.geometry}
          material={materials.standardSurface22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_5.geometry}
          material={materials.standardSurface4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_6.geometry}
          material={materials.standardSurface19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_7.geometry}
          material={materials.standardSurface3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_8.geometry}
          material={materials.standardSurface11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_9.geometry}
          material={materials.standardSurface15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_10.geometry}
          material={materials.standardSurface7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0001_11.geometry}
          material={materials.standardSurface12}
        />
      </group>
      <group
        position={[-1.795, 0.968, -0.22]}
        rotation={[-1.662, 1.276, 1.608]}
        scale={0.083}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0.geometry}
          material={materials.standardSurface5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_1.geometry}
          material={materials.standardSurface8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_2.geometry}
          material={materials.standardSurface6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_3.geometry}
          material={materials.standardSurface18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_4.geometry}
          material={materials.standardSurface22}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_5.geometry}
          material={materials.standardSurface4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_6.geometry}
          material={materials.standardSurface19}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_7.geometry}
          material={materials.standardSurface3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_8.geometry}
          material={materials.standardSurface11}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_9.geometry}
          material={materials.standardSurface15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_10.geometry}
          material={materials.standardSurface7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder15_standardSurface5_0_11.geometry}
          material={materials.standardSurface12}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/guitar.glb");
