/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { type JSX } from 'react'
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

type GLTFResult = {
  nodes: {
    surface: THREE.Mesh
  }
  materials: {
    concrete: THREE.MeshStandardMaterial
  }
}

export default function Surface(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/surface.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        scale={[2, 1, 2]}
        castShadow
        receiveShadow
        geometry={nodes.surface.geometry}
        material={materials.concrete}
      />
    </group>
  )
}

useGLTF.preload('/surface.glb')
