/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import type { GLTF } from "three/examples/jsm/Addons.js";
import type { JSX } from "react";

type GLTFResult = GLTF & {
  nodes: {
    Wall020_wall_concrete__0001_1: THREE.Mesh;
    Wall020_wall_concrete__0001_2: THREE.Mesh;
    Wall020_wall_concrete__0001_3: THREE.Mesh;
    Wall020_wall_concrete__0001_4: THREE.Mesh;
    Wall020_wall_concrete__0001_5: THREE.Mesh;
    Wall020_wall_concrete__0001_6: THREE.Mesh;
    Wall020_wall_concrete__0001_7: THREE.Mesh;
    Wall020_wall_concrete__0001_8: THREE.Mesh;
    Wall020_wall_concrete__0001_9: THREE.Mesh;
    Wall020_wall_concrete__0001_10: THREE.Mesh;
    Wall020_wall_concrete__0001_11: THREE.Mesh;
    Wall020_wall_concrete__0001_12: THREE.Mesh;
    Wall020_wall_concrete__0001_13: THREE.Mesh;
    Wall020_wall_concrete__0001_14: THREE.Mesh;
    Wall020_wall_concrete__0001_15: THREE.Mesh;
    Wall020_wall_concrete__0001_16: THREE.Mesh;
    Wall020_wall_concrete__0001_17: THREE.Mesh;
    Wall020_wall_concrete__0001_18: THREE.Mesh;
    Wall020_wall_concrete__0001_19: THREE.Mesh;
    Wall020_wall_concrete__0001_20: THREE.Mesh;
    Wall020_wall_concrete__0001_21: THREE.Mesh;
    Wall020_wall_concrete__0001_22: THREE.Mesh;
    Wall020_wall_concrete__0001_23: THREE.Mesh;
    Wall020_wall_concrete__0001_24: THREE.Mesh;
    Wall020_wall_concrete__0001_25: THREE.Mesh;
    Wall020_wall_concrete__0001_26: THREE.Mesh;
    Wall020_wall_concrete__0001_27: THREE.Mesh;
    Wall020_wall_concrete__0001_28: THREE.Mesh;
    Wall020_wall_concrete__0001_29: THREE.Mesh;
    Wall020_wall_concrete__0001_30: THREE.Mesh;
    Wall020_wall_concrete__0001_31: THREE.Mesh;
    Wall020_wall_concrete__0001_32: THREE.Mesh;
    Wall020_wall_concrete__0001_33: THREE.Mesh;
    Wall020_wall_concrete__0001_34: THREE.Mesh;
    Wall020_wall_concrete__0001_35: THREE.Mesh;
    Wall020_wall_concrete__0001_36: THREE.Mesh;
    Wall020_wall_concrete__0001_37: THREE.Mesh;
    Wall020_wall_concrete__0001_38: THREE.Mesh;
    Wall020_wall_concrete__0001_39: THREE.Mesh;
    Wall020_wall_concrete__0001_40: THREE.Mesh;
    Wall020_wall_concrete__0001_41: THREE.Mesh;
    Wall020_wall_concrete__0001_42: THREE.Mesh;
    Wall020_wall_concrete__0001_43: THREE.Mesh;
    Wall020_wall_concrete__0001_44: THREE.Mesh;
    Wall020_wall_concrete__0001_45: THREE.Mesh;
    Wall020_wall_concrete__0001_46: THREE.Mesh;
    Wall020_wall_concrete__0001_47: THREE.Mesh;
    Wall020_wall_concrete__0001_48: THREE.Mesh;
    Wall020_wall_concrete__0001_49: THREE.Mesh;
    Wall020_wall_concrete__0001_50: THREE.Mesh;
    Wall020_wall_concrete__0001_51: THREE.Mesh;
    Wall020_wall_concrete__0001_52: THREE.Mesh;
    Wall020_wall_concrete__0001_53: THREE.Mesh;
    Wall020_wall_concrete__0001_54: THREE.Mesh;
    Wall020_wall_concrete__0001_55: THREE.Mesh;
    Wall020_wall_concrete__0001_56: THREE.Mesh;
    Wall020_wall_concrete__0001_57: THREE.Mesh;
    Wall020_wall_concrete__0001_58: THREE.Mesh;
    Wall020_wall_concrete__0001_59: THREE.Mesh;
    Wall020_wall_concrete__0001_60: THREE.Mesh;
    Wall020_wall_concrete__0001_61: THREE.Mesh;
    Wall020_wall_concrete__0001_62: THREE.Mesh;
    Wall020_wall_concrete__0001_63: THREE.Mesh;
    Wall020_wall_concrete__0001_64: THREE.Mesh;
    Wall020_wall_concrete__0001_65: THREE.Mesh;
    Wall020_wall_concrete__0001_66: THREE.Mesh;
    Wall020_wall_concrete__0001_67: THREE.Mesh;
    Wall020_wall_concrete__0001_68: THREE.Mesh;
    Wall020_wall_concrete__0001_69: THREE.Mesh;
    Wall020_wall_concrete__0001_70: THREE.Mesh;
    Wall020_wall_concrete__0001_71: THREE.Mesh;
    Wall020_wall_concrete__0001_72: THREE.Mesh;
    Wall020_wall_concrete__0001_73: THREE.Mesh;
    Wall020_wall_concrete__0001_74: THREE.Mesh;
    Wall020_wall_concrete__0001_75: THREE.Mesh;
    Wall020_wall_concrete__0001_76: THREE.Mesh;
    Wall020_wall_concrete__0001_77: THREE.Mesh;
    Wall020_wall_concrete__0001_78: THREE.Mesh;
    Wall020_wall_concrete__0001_79: THREE.Mesh;
    Wall020_wall_concrete__0001_80: THREE.Mesh;
    Wall020_wall_concrete__0001_81: THREE.Mesh;
    Wall020_wall_concrete__0001_82: THREE.Mesh;
    Wall020_wall_concrete__0001_83: THREE.Mesh;
    Wall020_wall_concrete__0001_84: THREE.Mesh;
    Wall020_wall_concrete__0001_85: THREE.Mesh;
    Wall020_wall_concrete__0001_86: THREE.Mesh;
    Wall020_wall_concrete__0001_87: THREE.Mesh;
  };
  materials: {
    wall_concrete: THREE.MeshStandardMaterial;
    Blue: THREE.MeshStandardMaterial;
    metal_black: THREE.MeshStandardMaterial;
    // metal_grey_light: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    sticker_yellow: THREE.MeshStandardMaterial;
    // brown_light_3: THREE.MeshStandardMaterial;
    light_brown: THREE.MeshStandardMaterial;
    white_real: THREE.MeshStandardMaterial;
    Red_dark: THREE.MeshStandardMaterial;
    light_blue_2: THREE.MeshStandardMaterial;
    metal_grey_dark: THREE.MeshStandardMaterial;
    metal_grey: THREE.MeshStandardMaterial;
    light_blue: THREE.MeshStandardMaterial;
    Green: THREE.MeshPhysicalMaterial;
    Blue_dark: THREE.MeshStandardMaterial;
    Book_blue: THREE.MeshStandardMaterial;
    Comix_book_2: THREE.MeshStandardMaterial;
    Book_green: THREE.MeshStandardMaterial;
    Book_grey: THREE.MeshStandardMaterial;
    Book_red: THREE.MeshStandardMaterial;
    Red_2: THREE.MeshStandardMaterial;
    brown: THREE.MeshStandardMaterial;
    // brown_light_2: THREE.MeshStandardMaterial;
    Green_dark: THREE.MeshStandardMaterial;
    // brown_light: THREE.MeshStandardMaterial;
    dark_brown: THREE.MeshStandardMaterial;
    box_ammo_9mm: THREE.MeshStandardMaterial;
    box_ammo_9mm_piercing: THREE.MeshStandardMaterial;
    orange_contrst: THREE.MeshStandardMaterial;
    box_cardboard_big_closed: THREE.MeshStandardMaterial;
    box_cardboard_big_opened: THREE.MeshStandardMaterial;
    tincan_metal: THREE.MeshStandardMaterial;
    box_cardboard_medium_closed: THREE.MeshStandardMaterial;
    beanz_blue: THREE.MeshStandardMaterial;
    box_cardboard_medium_opened: THREE.MeshStandardMaterial;
    sticker_white: THREE.MeshStandardMaterial;
    beanz_red: THREE.MeshStandardMaterial;
    Blue_2: THREE.MeshStandardMaterial;
    Kitchen_cabinet_02: THREE.MeshStandardMaterial;
    glass: THREE.MeshStandardMaterial;
    Calendear: THREE.MeshStandardMaterial;
    Campbell_CreamOfBroccoli: THREE.MeshStandardMaterial;
    Campbell_CreamOfCelery: THREE.MeshStandardMaterial;
    Campbell_soup: THREE.MeshStandardMaterial;
    beanz_yellow: THREE.MeshStandardMaterial;
    Orange: THREE.MeshStandardMaterial;
    beanz_green: THREE.MeshStandardMaterial;
    clock_face_analog: THREE.MeshStandardMaterial;
    Code_lock: THREE.MeshStandardMaterial;
    // Green_light_emission: THREE.MeshStandardMaterial;
    Comix_book: THREE.MeshStandardMaterial;
    material_74: THREE.MeshStandardMaterial;
    Cutting_board: THREE.MeshPhysicalMaterial;
    Clock_face: THREE.MeshStandardMaterial;
    // Green_light: THREE.MeshStandardMaterial;
    Floor_concrete: THREE.MeshPhysicalMaterial;
    yellow_emmission_abajour: THREE.MeshStandardMaterial;
    yellow: THREE.MeshStandardMaterial;
    // white_emission: THREE.MeshStandardMaterial;
    // sticker_yellow_light: THREE.MeshStandardMaterial;
    // yellow_emission: THREE.MeshStandardMaterial;
    magazine_prettygirl: THREE.MeshStandardMaterial;
    material_51: THREE.MeshStandardMaterial;
    Plate: THREE.MeshStandardMaterial;
    Lethal_weapon: THREE.MeshStandardMaterial;
    Virus_posters: THREE.MeshStandardMaterial;
    Zoombie_posters: THREE.MeshStandardMaterial;
    Bunker_posters: THREE.MeshStandardMaterial;
    working_girl: THREE.MeshStandardMaterial;
    ["working_girl.003"]: THREE.MeshStandardMaterial;
    ["working_girl.001"]: THREE.MeshStandardMaterial;
    Visokoye_napr: THREE.MeshStandardMaterial;
    Shower: THREE.MeshStandardMaterial;
    Sink: THREE.MeshStandardMaterial;
    plinth: THREE.MeshStandardMaterial;
    Soda_blue: THREE.MeshStandardMaterial;
    Soda_green: THREE.MeshStandardMaterial;
    Soda_red: THREE.MeshStandardMaterial;
    Swanson_soup: THREE.MeshStandardMaterial;
    Toilet: THREE.MeshStandardMaterial;
    paper: THREE.MeshStandardMaterial;
    Led_Zeppelin_vinil: THREE.MeshStandardMaterial;
    Nirvana_vinil: THREE.MeshStandardMaterial;
    Rolling_Stones_vinil: THREE.MeshStandardMaterial;
    The_Jimi_Hendrix_vinil: THREE.MeshStandardMaterial;
    Van_Morrison_vinil: THREE.MeshStandardMaterial;
  };
};

export default function Warehouse(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/p3.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[0.188, -0.031, -1.816]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.006}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_1.geometry}
          material={materials.wall_concrete}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_2.geometry}
          material={materials.Blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_3.geometry}
          material={materials.metal_black}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_4.geometry}
          material={materials.metal_grey_light}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_5.geometry}
          material={materials.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_6.geometry}
          material={materials.sticker_yellow}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_7.geometry}
          material={materials.brown_light_3}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_8.geometry}
          material={materials.light_brown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_9.geometry}
          material={materials.white_real}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_10.geometry}
          material={materials.Red_dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_11.geometry}
          material={materials.light_blue_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_12.geometry}
          material={materials.metal_grey_dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_13.geometry}
          material={materials.metal_grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_14.geometry}
          material={materials.light_blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_15.geometry}
          material={materials.Green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_16.geometry}
          material={materials.Blue_dark}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_17.geometry}
          material={materials.Book_blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_18.geometry}
          material={materials.Comix_book_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_19.geometry}
          material={materials.Book_green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_20.geometry}
          material={materials.Book_grey}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_21.geometry}
          material={materials.Book_red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_22.geometry}
          material={materials.Red_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_23.geometry}
          material={materials.brown}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_24.geometry}
          material={materials.brown_light_2}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_25.geometry}
          material={materials.Green_dark}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_26.geometry}
          material={materials.brown_light}
        /> */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_27.geometry}
          material={materials.dark_brown}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_28.geometry}
          material={materials.box_ammo_9mm}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_29.geometry}
          material={materials.box_ammo_9mm_piercing}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_30.geometry}
          material={materials.orange_contrst}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_31.geometry}
          material={materials.box_cardboard_big_closed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_32.geometry}
          material={materials.box_cardboard_big_opened}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_33.geometry}
          material={materials.tincan_metal}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_34.geometry}
          material={materials.box_cardboard_medium_closed}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_35.geometry}
          material={materials.beanz_blue}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_36.geometry}
          material={materials.box_cardboard_medium_opened}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_37.geometry}
          material={materials.sticker_white}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_38.geometry}
          material={materials.beanz_red}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_39.geometry}
          material={materials.Blue_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_40.geometry}
          material={materials.Kitchen_cabinet_02}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_41.geometry}
          material={materials.glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_42.geometry}
          material={materials.Calendear}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_43.geometry}
          material={materials.Campbell_CreamOfBroccoli}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_44.geometry}
          material={materials.Campbell_CreamOfCelery}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_45.geometry}
          material={materials.Campbell_soup}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_46.geometry}
          material={materials.beanz_yellow}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_47.geometry}
          material={materials.Orange}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_48.geometry}
          material={materials.beanz_green}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_49.geometry}
          material={materials.clock_face_analog}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_50.geometry}
          material={materials.Code_lock}
        />
        {/* <mesh
          castShadow
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_51.geometry}
          material={materials.Green_light_emission}
        /> */}
        <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_52.geometry}
          material={materials.Comix_book}
        />
        <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_53.geometry}
          material={materials.material_74}
        />
        <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_54.geometry}
          material={materials.Cutting_board}
        />
        <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_55.geometry}
          material={materials.Clock_face}
        />
        {/* <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_56.geometry}
          material={materials.Green_light}
        /> */}
        <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_57.geometry}
          material={materials.Floor_concrete}
        />
        <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_58.geometry}
          material={materials.yellow_emmission_abajour}
        />
        <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_59.geometry}
          material={materials.yellow}
        />
        {/* <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_60.geometry}
          material={materials.white_emission}
        /> */}
        {/* <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_61.geometry}
          material={materials.sticker_yellow_light}
        /> */}
        {/* <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_62.geometry}
          material={materials.yellow_emission}
        /> */}
        <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_63.geometry}
          material={materials.magazine_prettygirl}
        />
        <mesh
          receiveShadow
          geometry={nodes.Wall020_wall_concrete__0001_64.geometry}
          material={materials.material_51}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_65.geometry}
          material={materials.Plate}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_66.geometry}
          material={materials.Lethal_weapon}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_67.geometry}
          material={materials.Virus_posters}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_68.geometry}
          material={materials.Zoombie_posters}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_69.geometry}
          material={materials.Bunker_posters}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_70.geometry}
          material={materials.working_girl}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_71.geometry}
          material={materials["working_girl.003"]}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_72.geometry}
          material={materials["working_girl.001"]}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_73.geometry}
          material={materials.Visokoye_napr}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_74.geometry}
          material={materials.Shower}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_75.geometry}
          material={materials.Sink}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_76.geometry}
          material={materials.plinth}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_77.geometry}
          material={materials.Soda_blue}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_78.geometry}
          material={materials.Soda_green}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_79.geometry}
          material={materials.Soda_red}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_80.geometry}
          material={materials.Swanson_soup}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_81.geometry}
          material={materials.Toilet}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_82.geometry}
          material={materials.paper}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_83.geometry}
          material={materials.Led_Zeppelin_vinil}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_84.geometry}
          material={materials.Nirvana_vinil}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_85.geometry}
          material={materials.Rolling_Stones_vinil}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_86.geometry}
          material={materials.The_Jimi_Hendrix_vinil}
        />
        <mesh
          geometry={nodes.Wall020_wall_concrete__0001_87.geometry}
          material={materials.Van_Morrison_vinil}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/p3.glb");
